#!/bin/sh
# Usage: matalbd stop
# Summary: Stops a currently running Matlab instance
# Help: Stops a currently running Matlab instance
# For information on running multiple Matlab instances at once,
# see `matlabd help`

echo "exit;" > $MATLABD_PIPE
if [ -e $MATLABD_TAILPIDFILE ]; then
    cat $MATLABD_TAILPIDFILE | xargs kill -9
fi
rm -f $MATLABD_PIPE $MATLABD_TAILPIDFILE
