#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _MATLABD_ROOT="$(abs_dirname "$libexec_path")"
export MATLABD_PIPE="$TMP/matlabd.pipe"
export MATLABD_TAILPIDFILE="$TMP/matlabd-tail.pid"
export MATLABD_OUT="/dev/null"
export MATLABD_ERR="/dev/null"
export MATLABD_CMDLOG="/dev/null"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec matlabd-help
  ;;
* )
  command_path="$(command -v "matlabd-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "matlabd: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
