#!/bin/sh
# Usage: matlabd start
# Summary: Starts a new Matlab instance
# Help: Starts a new Matlab instance. 
# For information on running multiple Matlab instances at once,
# see `matlabd help`

if ! [ -e $MATLABD_PIPE ]; then
    mkfifo $MATLABD_PIPE
    (tail -f $MATLABD_PIPE & echo $! >&3) 3>$MATLABD_TAILPIDFILE | matlab -nodisplay -nosplash >$MATLABD_OUT 2>$MATLABD_ERR &
fi
